### ISSUE TITLE
CMake Error: Could not find a package configuration file provided by "raisim" with any   of the following names

### ISSUE THREAD

**Issue by takayukikyk** [mayataka/idocp-sim#1]
I tried to clone idocp-sim and i tried to execute the following flow.

1. git clone https://github.com/mayataka/idocp-sim.git
2. cd idocp-sim && mkdir build && cd build
3. cmake .. -DCMAKE_BUILD_TYPE=Release 

But I couldn't successfully build it.
Here is the error message:
CMake Error at CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "raisim" with any
  of the following names:

    raisimConfig.cmake
    raisim-config.cmake

  Add the installation prefix of "raisim" to CMAKE_PREFIX_PATH or set
  "raisim_DIR" to a directory containing one of the above files.  If "raisim"
  provides a separate development package or SDK, be sure it has been
  installed.

I got a valid license and an activation key from [the RaiSim Tech website](https://raisim.com/sections/License.html) to use RaiSim and I referred to the [website](https://github.com/raisimTech/raisimOgre) and the installation of raisim and raisimOgre is complete.

so I don't know why it doesn't work and hope this question can be solved.

**Comment by mayataka** [comment]
Thank you for being interested in my repository.
Unfortunately, first of all, I'm sorry that this repo is under construction.
Currently, only the whole-body posture control is possible and it is not easy to carry on whole-body MPC for robot walking; it is my undergoing research.

Anyway, I can possibly answer your question. I guess you missed specifying PATH in CMake. 
If you followed https://raisim.com/sections/Installation.html and installed raisim and raisimOgre to, e.g., `~/raisim_build`, then you need to configure CMake as 
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/raisim_build
```
Otherwise, CMake cannot find raisim and raisimOgre.

**Comment by takayukikyk** [comment]
Thank you for your quick and polite response.
You've been a great help.
I've successfully completed make install.

I tried to execute example with the following flow.
1. cd idocp-sim/example/anymal && mkdir build && cd build
2. cmake ..  (I tried it on cmake .. -DCMAKE_BUILD_TYPE=Release )
3. make

But I couldn't successfully build it.
Here is the error message:

home/name/cmake_ws/src/idocp-sim/examples/anymal/posture.cpp:8:10: fatal error: idocp/ocp/ocp_solver.hpp: There are no such files or directories
 #include "idocp/ocp/ocp_solver.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/posture.dir/build.make:75: recipe for target 'CMakeFiles/posture.dir/posture.o' failed
make[2]: *** [CMakeFiles/posture.dir/posture.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/posture.dir/all' failed
make[1]: *** [CMakeFiles/posture.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

I have completed the installation of idocp and am able to run the examples anymal and iiwa14.
so I don't know why it doesn't work and hope this question can be solved.

I'm sorry for bothering you during your busy time. Thank you for your cooperation.

**Comment by mayataka** [comment]
It is because that this repo is not updated for the latest version of `idocp`. 
I also found that there are no instructions to run the posture control example.
Therefore, I'll fix this repo this week so that you can run the example of this repo.

**Comment by takayukikyk** [comment]
Thank you very much for your quick response.

**Comment by mayataka** [comment]
I fixed the source code; the updated one is in the devel branch.
Now you can try the example without installing idocp-sim.
Could you try the example? Currently, I'm not licensed from RaiSim.

**Comment by takayukikyk** [comment]
I appreciate your swift response.
I tried to execute example with the following flow, but it did not work.

1. git clone -b devel  https://github.com/mayataka/idocp-sim.git 　(# As for idocp-sim, I did not install anything new.)
2. cd idocp-sim/example/anymal && mkdir build && cd build
3. cmake .. (I tried it on cmake .. -DCMAKE_BUILD_TYPE=Release )
4. make 

But I couldn't successfully build it.
Here is the error message1:
*******************************************
/usr/bin/ld: -lProject cannot find.
collect2: error: ld returned 1 exit status
CMakeFiles/posture_control.dir/build.make:153: recipe for target 'posture_control' failed
make[2]: *** [posture_control] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/posture_control.dir/all' failed
make[1]: *** [CMakeFiles/posture_control.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
*******************************************
From the warning message in step 3, the following message was added to[ /idocp-sim/examples/anymal/CMakeLists.txt  ](https://github.com/mayataka/idocp-sim/blob/main/examples/anymal/CMakeLists.txt)and the above procedure was performed again.
```
cmake_minimum_required(VERSION 3.1) 
project(idocp_examples_position CXX)
```
The warning message in step 3 is gone, but the error message is displayed as well.
Here is the error message2:
*******************************************
/usr/bin/ld: -lidocp_examples_position cannot find
collect2: error: ld returned 1 exit status
CMakeFiles/posture_control.dir/build.make:153: recipe for target 'posture_control' failed
make[2]: *** [posture_control] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/posture_control.dir/all' failed
make[1]: *** [CMakeFiles/posture_control.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
*******************************************

I think I need to set the project name properly, but I don't know how to do it.
I would appreciate it if you give me instructions.

**Comment by mayataka** [comment]
I intend to build the example as the "subdirectory" (a term in CMake) of the CMake project `idocp-sim`.
Could you simply build `idocp-sim` again as the following?
```
git clone -b devel https://github.com/mayataka/idocp-sim.git
cd idocp-sim && mkdir build && cd build
cmake .. (write options here) 
make -j
```
Then the executable file will be generated at build/examples/anymal/.

**Comment by takayukikyk** [comment]
Thanks to you. I successfully generated the executable file.
When I run it, there is a raisim related error, which is being addressed. I will contact you as soon as it is resolved.

**Comment by mayataka** [comment]
Could you share the issue?
If it is related to the PATHs such as of license file or URDF (sometimes RaiSim requires absolute PATH rather than relative PATH), I'll fix it.

**Comment by takayukikyk** [comment]
Thank you for your kindness.
I tried to run with the following command.
`./posture_control ~/.raisim/activation.raisim`
Here is the error message:
***************************************
The license was issued to another machine
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(maybe the machine ID)
***************************************
But this error message will also occur if I run [raisimExample](https://github.com/raisimTech/raisimExample).
I am wondering if there is a problem with the raisim license and am inquiring about **[it](https://github.com/raisimTech/raisimExample/issues/3).**

**Comment by mayataka** [comment]
Thank you for sharing.
As you said, the error seems due to raisim.
The only thing I wondering is that what happens if we specify the absolute PATH for the license file, e.g.,
```
./posture_control /home/username/.raisim/activation.raisim
```

**Comment by takayukikyk** [comment]
I tried it.
The same error message appeared as well.

**Comment by takayukikyk** [comment]
I successfully resolved the error regarding raisim and tried execute sample program with the following command.
`./posture_control /home/username/.raisim/activation.raisim`

However the following error message appeared.
Here is the error message:
*****************************************
 Loading RaisimOgre Resources from: 
 Loading OGRE Configurations from: /home/username/raisim_build/share/raisimOgre/cmake/../ogre/
sim_results/posture.mp4: No such file or directory
*****************************************

I created a directory named `sim_results` as a test, but there was no change in the error message.

I would appreciate any help on how to resolve this.

**Comment by mayataka** [comment]
The latest commit on `devel` branch may resolve this problem.

**Comment by takayukikyk** [comment]
I appreciate your swift response.
When `./posture_control /home/username/.raisim/activation.raisim` is executed, Segmentation fault (Core dump) is output.

I currently investigating the cause of the problem, but I don't know.

**Comment by mayataka** [comment]
I could run the example in my environment.
One possible reason is that you build idocp with `-DOPTIMIZE_FOR_NATIVE=ON` but raisim without `-march=native`, or vice versa.
You should unify the vectorization option between the linked libraries, that is, if you built raisim without `-march=native`, you must build idocp with `-DOPTIMIZE_FOR_NATIVE=OFF`.
There can be other reasons, but I cannot come up with them.

**Comment by takayukikyk** [comment]
Thank you for your instruction.
I built idocp with `-DOPTIMIZE_FOR_NATIVE=OFF` until a little while ago.
I tried building with `-DOPTIMIZE_FOR_NATIVE=ON`.
But result did not change.

I'm a bit ashamed to ask this but how do I set raisim without `-march=native`

You must be very busy, but it would be great if you could let me know your thoughts on the questions.

**Comment by mayataka** [comment]
I'm not sure but I gguess that the default setting of raisim does not involve `-march=native` because the default setting of CMake does not declare `-march=native`.

**Comment by takayukikyk** [comment]
Thank you for your answer.
I will continue to look into the cause of the problem.

**Comment by mayataka** [comment]
Since the issues are resolved at least in my environment, I'll close this issue.
If you have any other problems, feel free to reopen this issue.

**Comment by mayataka** [comment]
@takayukikyk 
Now `idocp` has a Python interface and you need not use C++ simulators including `RaiSim`.
For example, you can simulate MPC with `PyBullet` (see https://github.com/mayataka/idocp).

**Comment by mayataka** [comment]
Therefore, this repo is no longer maintained.
